Description: 'Effective DevOps in AWS: HelloWorld web application'
Outputs:
  DomainName:
    Description: DNS using instance ID
    Value: !Ref 'myDNSRecord'
  InstancePublicIp:
    Description: Public IP of our instance.
    Value: !GetAtt 'instance.PublicIp'
  WebUrl:
    Description: Application endpoint
    Value: !Join
      - ''
      - - http://
        - !Ref 'myJenkinsDNSRecord'
        - ':'
        - '8080'
Parameters:
  HostedZone:
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    Type: String
  KeyPair:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to SSH
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  CodepipelinePolicy:
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codepipeline:*
            Effect: Allow
            Resource:
              - '*'
      PolicyName: AllowsCodePipeline
      Roles:
        - !Ref 'Role'
    Type: AWS::IAM::Policy
  InstanceProfile:
    Properties:
      Path: /
      Roles:
        - !Ref 'Role'
    Type: AWS::IAM::InstanceProfile
  Role:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      Description: Role for add SSM capabilities to Jenkins instance
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    Type: AWS::IAM::Role
  S3Policy:
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - '*'
      PolicyName: AllowsS3
      Roles:
        - !Ref 'Role'
    Type: AWS::IAM::Policy
  SecurityGroup:
    Properties:
      GroupDescription: Allow SSH and TCP/8080 access
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
        - CidrIp: '0.0.0.0/0'
          FromPort: '8080'
          IpProtocol: tcp
          ToPort: '8080'
    Type: AWS::EC2::SecurityGroup
  instance:
    Properties:
      IamInstanceProfile: !Ref 'InstanceProfile'
      ImageId: ami-0c2b8ca1dad447f8a
      InstanceType: t2.micro
      KeyName: !Ref 'KeyPair'
      SecurityGroups:
        - !Ref 'SecurityGroup'
      UserData: !Base64
        Fn::Join:
          - "\n"
          - - '#!/bin/bash'
            - sudo systemctl enable amazon-ssm-agent
            - sudo systemctl start amazon-ssm-agent
            - yum install -y git
            - sudo amazon-linux-extras install -y ansible2
            - /usr/bin/ansible-pull -U https://github.com/jarmandomtz/ansible-pull-gitrepo
              jenkins.yml -C develop -i localhost -v --sleep 60 >> /tmp/ansible-pull.log
            - >-
              echo '*/2 * * * * /usr/bin/ansible-pull -U https://github.com/jarmandomtz/ansible-pull-gitrepo
              jenkins.yml -C develop -i localhost -v --sleep 60 >> /tmp/ansible-pull.log'
              > /tmp/ansible-pull-crontab-cmd
            - sudo crontab -u ec2-user /tmp/ansible-pull-crontab-cmd
            - sudo mkdir -p /tmp/bkps
            - sudo aws s3 cp s3://esausi-backups/jenkins/backup_2021_09_12_20_01_18_245.pbobj
              /tmp/bkps/
            - sudo aws s3 cp s3://esausi-backups/jenkins/backup_2021_09_12_20_01_18_245.tar.gz
              /tmp/bkps/
            - sudo chown -R jenkins /tmp/bkps
            - sudo chgrp -R jenkins /tmp/bkps
    Type: AWS::EC2::Instance
  myDNSRecord:
    Properties:
      Comment: DNS name for my instance.
      HostedZoneName: !Join
        - ''
        - - !Ref 'HostedZone'
          - .
      Name: !Join
        - ''
        - - !Ref 'instance'
          - .
          - !Ref 'AWS::Region'
          - .
          - !Ref 'HostedZone'
          - .
      ResourceRecords:
        - !GetAtt 'instance.PublicIp'
      TTL: '900'
      Type: A
    Type: AWS::Route53::RecordSet
  myJenkinsDNSRecord:
    Properties:
      Comment: DNS name for my instance.
      HostedZoneName: !Join
        - ''
        - - !Ref 'HostedZone'
          - .
      Name: !Join
        - ''
        - - jenkins
          - .
          - !Ref 'HostedZone'
          - .
      ResourceRecords:
        - !GetAtt 'instance.PublicIp'
      TTL: '900'
      Type: A
    Type: AWS::Route53::RecordSet

